"""The sentinels and their producers, in the same file.

Doctrine rule 5.6, and class B of the register with three cases:

  B1  the banner "GENERADO POR `aegis org`" was written out eight times
      as a literal, and the GUARD that decides whether a derived file
      was hand-edited looked for it with an `in` (aegis-org:1165).
      Changing the wording in the producer and not in the guard breaks
      nothing visible: the guard stops recognising its own files, and
      hand edits start being overwritten in silence.
  B2  the jobs/probes block markers, a derived block living inside
      somebody else's values.yaml: whoever writes the block and whoever
      finds it again must use exactly the same string, down to the
      leading spaces (they sit inside YAML — the indentation is part of
      the sentinel).
  B3  the orchestrator's "Resume:" line, which a check reads to confirm
      the resume message exists.

The rule is simple: if two parts of the system must recognise the same
string, that string lives ONCE and both import it. Check V-105 refuses
to let anyone write it out by hand again.
"""
import re

# ── the banner of derived files ──────────────────────────────────────
# It is searched for by this substring, not by the whole drawing: the
# box frame can change width without the meaning changing.
GENERATED_SIGNATURE = "GENERATED BY `aegis org`"

# The frame is BUILT, not typed. In v2 it was eight hand-drawn copies
# and the alignment was a matter of counting characters correctly —
# which is exactly the kind of thing that survives one translation and
# breaks on the next. Now the width follows the text.
_TITLE = GENERATED_SIGNATURE + " — DO NOT EDIT BY HAND"
_WIDTH = 66
FRAME = [
    "# ╔" + "═" * _WIDTH + "╗",
    "# ║  " + _TITLE.ljust(_WIDTH - 2) + "║",
    "# ╚" + "═" * _WIDTH + "╝",
]
BANNER = "\n".join(FRAME)

HEADER = BANNER + """
# What you change is the contract, and then you reapply:
#
#     $EDITOR orgs/{org}.yaml
#     aegis org apply orgs/{org}.yaml
#
# contract: orgs/{org}.yaml
# hash: sha256:{hash}
"""

# The hash line is written in one place and ignored in another (to
# compare two renderings "except for the hash"). One prefix, once.
HASH_PREFIX = "# hash: sha256:"


def is_generated(text: str) -> bool:
    """Did the generator write this file? The question the guard asks
    before overwriting anything."""
    return GENERATED_SIGNATURE in text


def without_hash(text: str) -> str:
    """The text minus its hash line, so content can be compared."""
    return "\n".join(l for l in text.splitlines() if not l.startswith(HASH_PREFIX))


# ── derived blocks inside somebody else's file ───────────────────────
# The indentation is part of the sentinel: these blocks live INSIDE a
# YAML (jenkins' and vmagent's values.yaml), and with different
# indentation the file stops parsing.
JOBS_BLOCK_START = "          # --- DERIVED by aegis-org (tenant jobs): do not edit by hand ---"
JOBS_BLOCK_END = "          # --- END DERIVED ---"
PROBES_BLOCK_START = "    # --- DERIVED by aegis-org (tenant probes): do not edit by hand ---"
PROBES_BLOCK_END = "    # --- END DERIVED ---"

JOBS_BLOCK_PATTERN = re.compile(
    re.escape(JOBS_BLOCK_START) + r"\n(?:.*\n)*?" + re.escape(JOBS_BLOCK_END))
PROBES_BLOCK_PATTERN = re.compile(
    re.escape(PROBES_BLOCK_START) + r"\n(?:.*\n)*?" + re.escape(PROBES_BLOCK_END))

# ── the base-images consumers, a derived block in a plain-text list ──
# NO indentation, on purpose: base-images/consumers.txt is not YAML. It
# is read by the base-images Jenkins pipeline with `grep`, one
# repository URL per line, and it skips lines that start with `#`. So
# the sentinels are comments at column 0 and the body between them is
# nothing but URLs — no header comment, no blank line, no "(none)"
# placeholder — because anything else would reach the pipeline as a
# repository to clone. The list exists because of 2026-08-26: a CVE in
# a shared base left four static fronts frozen, each waiting for a
# person to bump the same FROM by hand in four repos; the derived list
# is what lets the base-images job do that edit itself.
CONSUMERS_BLOCK_START = "# --- DERIVED by aegis-org (base consumers): do not edit by hand ---"
CONSUMERS_BLOCK_END = "# --- END DERIVED ---"

CONSUMERS_BLOCK_PATTERN = re.compile(
    re.escape(CONSUMERS_BLOCK_START) + r"\n(?:.*\n)*?" + re.escape(CONSUMERS_BLOCK_END))

# ── the orchestrator's sentinel ──────────────────────────────────────
# aegis-init prints it when a phase fails, and check 73 looks for it.
# The shape matters: it has to be pasteable from any directory.
RESUME_PREFIX = "Resume:"
