#!/usr/bin/env bash
# harness/org-equivalence.sh — the move did not change the MEANING.
#
# `aegis org` derives from each organization's contract everything it
# needs: bundle, netpol, routes, appproject, Jenkins jobs, probes,
# buckets. Moving it into the product and putting a package underneath
# (paths, markers, conf) is touching the most expensive file in the
# system, and the proof worth having is to render the FOUR REAL
# contracts of the v2 instance with both generators and compare.
#
# ── WHY IT NO LONGER COMPARES CHARACTERS (rewritten 2026-08-25) ──────
# Until today this compared byte for byte, and it had been reporting
# «4 real contracts rendered · 0 generated files · byte for byte
# identical» IN GREEN. Zero files. Both generators were dying on a file
# they could not find —the rename had left this harness copying v3's
# names out of a v2 instance that has v2's— and `>/dev/null 2>&1` was
# hiding it. A test that compares nothing and reports success is the
# exact disease this verifier exists to kill, and it was living inside
# the verifier.
#
# Making it honest showed the deeper problem: byte-for-byte equivalence
# with v2 IS ALREADY FALSE ON PURPOSE. v3's banner says GENERATED BY,
# argocd's secret-generator is now generated where v2 wrote it by hand,
# and the whole product is being translated into English. Keeping the
# old premise green would mean growing a normalisation layer that
# erases precisely the differences that were decided — tuning the test
# until it passes, which is worse than having none.
#
# So the question is narrowed to the one that survives: do the two
# generators produce the SAME OBJECTS? Comments, wording and formatting
# are outside the comparison; kinds, names, namespaces, labels, specs
# and every value are inside it. That is what catches the failure this
# exists for — a comma in the derivation that moves 35 generated files
# at once.
#
# WHAT IT DOES NOT COVER, and who does: the global artifacts (main.tf's
# public_hostnames, the derived blocks inside jenkins' and vmagent's
# values, tenants.yaml, appprojects-tenants.yaml) are measured by check
# 113, which demands the seed be a fixed point of the generator with
# zero organizations. Here the WITH-CONTRACTS path is measured, which
# is the one 113 cannot reach.
set -u
: "${AEGIS_ROOT:?}"
V2="${AEGIS_V2:-$HOME/Escritorio/workspace/aegis-v2}"
ORG_V2="$V2/platform/bin/aegis-org"
PLAT="$V2/platform"
CONF="$V2/init/aegis-init.conf"

if [[ ! -x "$ORG_V2" || ! -d "$PLAT/orgs" ]]; then
    echo "COULD NOT EVALUATE: I cannot find the reference ($ORG_V2 / $PLAT/orgs)" >&2
    echo "  — with AEGIS_V2=<path> you can tell it where it is" >&2
    exit 2
fi

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# The retired-name table, read from the law: §3 (enforced) and §3b
# (being retired) of docs/glossary.md. Derived and not copied here, so
# a name that moves tomorrow reaches this harness without anybody
# remembering it exists.
_renames() {
    sed -n '/^## 3\. /,/^## 4\. /p' "$AEGIS_ROOT/docs/glossary.md" \
        | sed -n 's/^| `\([^`]*\)` | `\([^`]*\)` |.*/\1>\2/p'
}

# $1 = destination, $2 = flavour (v2 keeps the instance's names; v3 gets
# the ones its generator looks for). The flavour is the whole point:
# the reference reads `planes.yaml` and `dominio_raiz`, the subject
# reads `plans.yaml` and `root_domain`, and rewriting BOTH is what
# broke the reference a moment ago.
build_copy() {
    local d="$1" flavour="$2" was is_ f alias
    mkdir -p "$d/ai" "$d/tofu/envs/cloudflare-tunnel" "$d/docs/protocols" "$d/bin"
    cp -a "$PLAT/orgs" "$PLAT/k8s" "$d/"
    cp -a "$PLAT"/*.yaml "$d/"
    # The WHOLE ai/ directory and not a list of names: naming them is
    # what left this harness copying files that do not exist.
    cp -a "$PLAT/ai/." "$d/ai/" 2>/dev/null
    cp -a "$PLAT/tofu/envs/cloudflare-tunnel/main.tf" "$d/tofu/envs/cloudflare-tunnel/" 2>/dev/null
    cp -a "$PLAT/docs/protocols/templates" "$d/docs/protocols/" 2>/dev/null
    cp -a "$ORG_V2" "$d/bin/"
    [[ "$flavour" == v3 ]] || return 0

    while IFS='>' read -r was is_; do
        was="${was// /}"; is_="${is_// /}"
        [[ -n "$was" && -n "$is_" ]] || continue
        # file names of the CONFIG it reads — never the manifests. An
        # earlier version aliased the whole tree and invented an
        # org-canary/routes.yaml that no generator had written, then
        # reported it as a difference.
        for f in "$d"/*.yaml "$d"/ai/*.yaml; do
            [[ -f "$f" ]] || continue
            alias="${f//$was/$is_}"
            [[ "$alias" != "$f" && ! -e "$alias" ]] && cp -a "$f" "$alias"
        done
        # and the KEYS inside the config it reads: edge.yaml's
        # `dominio_raiz` is `root_domain` now, and v3 dies with
        # KeyError on the instance's file. Only rows shaped like a yaml
        # key, and only in config — never in a manifest, where the same
        # word could be data.
        if [[ "$was" =~ ^[a-z][a-z0-9_]*$ ]]; then
            for f in "$d"/*.yaml "$d"/ai/*.yaml; do
                [[ -f "$f" ]] && sed -i "s/^\( *\)${was}:/\1${is_}:/" "$f"
            done
        fi
    done < <(_renames)
}

build_copy "$TMP/v2" v2 ; cp -a "$TMP/v2" "$TMP/v2-base"
build_copy "$TMP/v3" v3 ; cp -a "$TMP/v3" "$TMP/v3-base"

CONTRACTS=("$PLAT"/orgs/*.yaml)
[[ -e "${CONTRACTS[0]}" ]] || { echo "COULD NOT EVALUATE: zero contracts in $PLAT/orgs" >&2; exit 2; }

v3org() { PLATFORM_DIR="$TMP/v3" AEGIS_CONF="$CONF" AEGIS_ROOT="$AEGIS_ROOT" \
              "$AEGIS_ROOT/libexec/aegis-org" "$@"; }

# The generators DO NOT run blind. A stage that fails is REPORTED and
# does not abort the comparison: `apply_jenkins` legitimately refuses
# against the v2 instance (its values carries no derived-block markers,
# which is the defect check 113 found on 2026-08-25), and the
# per-organization manifests — the ones measured here — are written
# before it.
note_side() {
    local who="$1"; shift
    local out; out="$("$@" 2>&1)" || \
        printf '  \033[1;33m!\033[0m %s: %s\n' "$who" "$(printf '%s' "$out" | grep -m1 '✗' || printf '%s' "$out" | tail -1)"
}
for c in "${CONTRACTS[@]}"; do
    n="$(basename "$c")"
    note_side "v2 $n" bash -c "cd '$TMP/v2' && ./bin/aegis-org aplicar 'orgs/$n'"
    note_side "v3 $n" v3org apply "$TMP/v3/orgs/$n"
done

export LC_ALL=C

# The comparison, per organization and by STRUCTURE. Both trees are
# parsed and their documents indexed by (kind, namespace, name), so
# that a reordering is not a difference and a missing object is.
_renames > "$TMP/renames.txt"
python3 - "$TMP/v2" "$TMP/v3" "$TMP/renames.txt" <<'PY'
import pathlib, sys, yaml

v2, v3 = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
# org-canary is EXCLUDED: it has no contract, so neither generator
# writes it — its manifests are hand-written source, and comparing
# them here would only measure the copy operation. That the canary's
# copies match the generator is check 091b's job.
GLOB = "k8s/organizations/org-*/*.yaml"
SKIP = "org-canary"

# The DECLARED differences, read from docs/glossary.md — never a list
# tuned here until the test passes. A name the law says has been
# retired is normalised on the reference's side; anything the law does
# not name stays a difference, which is the whole point.
RENAMES = []
for line in pathlib.Path(sys.argv[3]).read_text().splitlines():
    was, _, is_ = line.partition(">")
    if was.strip() and is_.strip():
        RENAMES.append((was.strip(), is_.strip()))
# Longest first: a row whose «was» is a prefix of another's would
# otherwise win and leave the longer one half-substituted.
RENAMES.sort(key=lambda r: -len(r[0]))


# Only strings that ARE a file name. The glossary's §3/§3b rows that
# matter here renamed FILES, and applying them as bare substrings
# reached into object names too: v2's `blog-ruteo` IngressRoute became
# `blog-routes` and the harness reported a difference against a v3 that
# emits `blog-ruteo` exactly like v2. The `-ruteo` suffix has NOT been
# retired — that is the contract vocabulary, and it moves as one piece
# or not at all.
_FILE = (".yaml", ".yml", ".py", ".mjs", ".txt", ".tpl", ".sh")


def normalise(x):
    """v2's output, with the file renames the glossary declares applied."""
    if isinstance(x, str):
        if not x.endswith(_FILE):
            return x
        for was, is_ in RENAMES:
            x = x.replace(was, is_)
        return x
    if isinstance(x, list):
        return [normalise(v) for v in x]
    if isinstance(x, dict):
        return {normalise(k): normalise(v) for k, v in x.items()}
    return x


def docs(p, apply_renames=False):
    try:
        out = [d for d in yaml.safe_load_all(p.read_text()) if isinstance(d, dict)]
    except (OSError, yaml.YAMLError):
        return None
    return [normalise(d) for d in out] if apply_renames else out


def key(d):
    m = d.get("metadata") or {}
    return (d.get("kind"), m.get("namespace", ""), m.get("name", ""))


# ── DELIBERATE divergences from v2 ──────────────────────────────────
# This harness measures "v3 emits what v2 emits", and that premise has
# an expiry date written in its own header: the day v3 improves on v2,
# the difference is the POINT and not the defect. What must never happen
# is that such a difference goes unnoticed — so it is DECLARED here,
# with the reason, and anything not on this list is still a failure.
#
# A row is (path suffix, why). It only silences the exact path.
DELIBERATE = [
    (".spec.entryPoints",
     "v3 emits [web, websecure] on both edges and v2 only [web]: with "
     "EDGE=local the host bridge hands 443 to traefik and the route has "
     "to be served there. Under cloudflare nothing reaches 443, so the "
     "extra entryPoint is inert — the manifest serves both edges, which "
     "is what lets the seed stay one shape (T-04a, 2026-08-26)"),
]


def deliberate(path):
    for suffix, why in DELIBERATE:
        if path.endswith(suffix):
            return why
    return None


def diff(want, got, path):
    if isinstance(want, dict) and isinstance(got, dict):
        for k in sorted(set(want) | set(got)):
            if k not in got:
                return f"{path}.{k} missing in v3"
            if k not in want:
                return f"{path}.{k} left over in v3"
            d = diff(want[k], got[k], f"{path}.{k}")
            if d:
                return d
        return None
    if isinstance(want, list) and isinstance(got, list):
        if len(want) != len(got):
            why = deliberate(path)
            if why:
                DECLARED.append((path, why))
                return None
            return f"{path}: v2 has {len(want)} items, v3 has {len(got)}"
        for i, (a, b) in enumerate(zip(want, got)):
            d = diff(a, b, f"{path}[{i}]")
            if d:
                return d
        return None
    if want != got:
        why = deliberate(path)
        if why:
            DECLARED.append((path, why))
            return None
        return f"{path}: v2 {want!r} · v3 {got!r}"
    return None


compared, bad = 0, []
DECLARED = []
for f3 in sorted(v3.glob(GLOB)):
    if SKIP in f3.parts:
        continue
    rel = f3.relative_to(v3)
    # EVERYTHING under k8s/organizations/org-*/ is generated by
    # definition, so there is nothing to filter. The first version
    # skipped whatever matched its pristine copy, meaning it silently
    # dropped every file the generator reproduced identically — which
    # is most of them, and exactly the ones worth comparing. It looked
    # at 4 of 24.
    # v2's twin may be under the OLD name: `routes.yaml` there is
    # still `ruteo.yaml`. The path is un-renamed to find it, with the
    # same table — the difference in NAME is declared; what is
    # compared is what is inside.
    rel2 = str(rel)
    for was, is_ in RENAMES:
        if is_ in rel2 and (v2 / rel2.replace(is_, was)).exists():
            rel2 = rel2.replace(is_, was)
            break
    a, b = docs(v2 / rel2, apply_renames=True), docs(f3)
    if a is None:
        bad.append(f"{rel}: v2 did not write it (only v3 did)")
        continue
    compared += 1
    ia = {key(d): d for d in a}
    ib = {key(d): d for d in b}
    for k in sorted(set(ia) | set(ib), key=str):
        if k not in ib:
            bad.append(f"{rel}: v3 does NOT emit {k}")
        elif k not in ia:
            bad.append(f"{rel}: v3 emits {k}, which v2 does not")
        else:
            d = diff(ia[k], ib[k], "/".join(x for x in k if x))
            if d:
                bad.append(f"{rel}: {d}")

# ZERO compared files is NOT success. That is how this harness spent a
# day green while measuring nothing.
if compared == 0:
    print("  \033[1;31m✗\033[0m NOT ONE generated file was compared: both "
          "generators left the tree as it was, so this measured nothing")
    sys.exit(1)

# The declared divergences are PRINTED, never swallowed. A silenced
# difference that nobody sees is the same as no comparison at all —
# which is exactly the state this harness spent a day in.
seen = set()
for path, why in DECLARED:
    if why in seen:
        continue
    seen.add(why)
    print(f"  \033[1;33m~\033[0m DELIBERATE divergence from v2 ({path}): {why}")

for m in bad[:8]:
    print(f"  \033[1;31m✗\033[0m {m}")
if bad:
    print(f"  {len(bad)} structural differences over {compared} generated files")
    sys.exit(1)
print(f"  \033[1;32m✓\033[0m {compared} generated files from real contracts: "
      "same objects, same fields, same values")
PY
