# teeth for check 105 (the sentinels live in one single place)
# Class B: the banner was written eight times and the guard looked for
# it with an `in`. Changing it on one side and not the other leaves the
# guard unable to recognize its own files, and hand edits get overwritten.
red_1() {
    printf '\nANOTHER_COPY = "# ║  GENERATED BY `aegis org` — DO NOT EDIT BY HAND ║"\n' \
        >> "$AEGIS_ROOT/lib/aegis/org.py"
}
red_2() { sed -i 's/markers\.is_generated(old)/"GENERATED BY `aegis org`" in old/' "$AEGIS_ROOT/lib/aegis/org.py"; }
