// aprovisionar.mjs — gives an organization its bucket and its
// permission on the shared Garage.
//
// IDEMPOTENT AND DEPENDENCY-FREE. Dependency-free because it runs on
// nodejs-distroless, which is already mirrored and signed: pulling and
// signing a new image just to speak HTTP would be one more link in the
// supply chain in exchange for nothing.
//
// THE KEY is generated by aegis and this script IMPORTS it. The other
// way round —letting Garage generate it— a re-apply would produce a
// different credential every time and it would have to be written back
// somewhere. With the material in git (encrypted), running this twice
// changes nothing, which is rule I2 of the protocol.
const ADMIN  = process.env.GARAGE_ADMIN;
const TOKEN  = process.env.GARAGE_ADMIN_TOKEN;
const ORG    = process.env.ORG;
const BUCKET = process.env.BUCKET;
const KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const KEY_SEC= process.env.AWS_SECRET_ACCESS_KEY;

for (const [k, v] of Object.entries({ADMIN, TOKEN, ORG, BUCKET, KEY_ID, KEY_SEC})) {
  if (!v) { console.error(`missing ${k}`); process.exit(2); }
}

// ── WAIT UNTIL THE NETWORK IS READY ───────────────────────────────
//
// This Job runs as a sync hook and starts within seconds of coming
// into existence. The NetworkPolicies that authorize it to talk to
// Garage are programmed by the CNI REACTING to the pod, and that
// programming is not instantaneous: there is a window in which the pod
// is already running and its traffic is still refused.
//
// MEASURED on 2026-08-04, on the first real provisioning (org-ejemplo):
// all three attempts of the Job failed with ECONNREFUSED within 33
// seconds, and an identical probe launched afterwards connected on the
// first try, at t+0s. The policy was right from the start; what was
// missing was time.
//
// And the symptom misleads: in k3s the CNI REJECTS instead of dropping,
// so it gives ECONNREFUSED and not a timeout. "Connection refused"
// reads as "the service is down", which sends you to look at Garage
// —where nothing is broken— instead of at the network.
//
// That is why the retry lives HERE and not in the Job's backoffLimit:
// retrying the whole pod pays the startup cost all over again and burns
// the three attempts inside the same window. The backoffLimit is left
// for what really is an error.
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function withRetry(label, fn) {
  const DEADLINE_MS = 180_000;
  const t0 = Date.now();
  let delay = 2000, attempt = 0;
  for (;;) {
    attempt++;
    try {
      return await fn();
    } catch (e) {
      // ONLY NETWORK failures are retried. A 400 from Garage is not a
      // connectivity problem and retrying it for three minutes merely
      // delays the real error; those never even reach here, because
      // fetch resolves and the status code is read by the caller.
      const code = e.cause?.code || e.name || "";
      const transient = /ECONNREFUSED|ECONNRESET|EHOSTUNREACH|ENETUNREACH|ETIMEDOUT|EAI_AGAIN|TimeoutError|AbortError/.test(code);
      const elapsed = Date.now() - t0;
      if (!transient || elapsed > DEADLINE_MS) {
        console.error(`${label}: ${code || e.message} after ${Math.round(elapsed / 1000)}s` +
                      (transient ? " — the network never opened up" : ""));
        throw e;
      }
      console.log(`${label}: ${code}, retry ${attempt} in ${delay / 1000}s ` +
                  `(t+${Math.round(elapsed / 1000)}s)`);
      await sleep(delay);
      delay = Math.min(delay * 2, 15_000);
    }
  }
}

async function api(op, body) {
  const r = await withRetry(`POST ${op}`, () =>
    fetch(`${ADMIN}/v2/${op}`, {
      method: "POST",
      headers: {Authorization: `Bearer ${TOKEN}`, "Content-Type": "application/json"},
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(10_000),
    }));
  const txt = await r.text();
  return {ok: r.ok, status: r.status, txt};
}

// Errors are told apart by CONTENT and not only by code: Garage answers
// 400 both for "it already exists" and for "you asked for nonsense",
// and treating the two alike would turn a real error into a silent
// success. It is exactly the class of guard this project has already
// had to fix four times.
const alreadyExists = (t) => /already exist|already in use|Key name conflict/i.test(t);

let r = await api("CreateBucket", {globalAlias: BUCKET});
if (r.ok)                      console.log(`bucket ${BUCKET}: created`);
else if (alreadyExists(r.txt)) console.log(`bucket ${BUCKET}: already existed`);
else { console.error(`CreateBucket ${r.status}: ${r.txt}`); process.exit(1); }

r = await api("ImportKey", {accessKeyId: KEY_ID, secretAccessKey: KEY_SEC, name: `org-${ORG}`});
if (r.ok)                      console.log(`key for org-${ORG}: imported`);
else if (alreadyExists(r.txt)) console.log(`key for org-${ORG}: already existed`);
else { console.error(`ImportKey ${r.status}: ${r.txt}`); process.exit(1); }

// The PERMISSION is asked for by bucket ID, not by alias. An alias is a
// readable name, there can be several of them and they can change; the
// id is the bucket. (Measured: AllowBucketKey with the alias answers
// 400 "Invalid bucket id: Invalid character 'p' at position 0", which
// is an honest message but not an obvious one until you read it.)
const info = await withRetry("GET GetBucketInfo", () =>
  fetch(`${ADMIN}/v2/GetBucketInfo?globalAlias=${encodeURIComponent(BUCKET)}`,
    {headers: {Authorization: `Bearer ${TOKEN}`}, signal: AbortSignal.timeout(10_000)}));
if (!info.ok) { console.error(`GetBucketInfo ${info.status}: ${await info.text()}`); process.exit(1); }
const bucketId = (await info.json()).id;
if (!bucketId) { console.error("GetBucketInfo returned no id"); process.exit(1); }

// Permission ONLY over its own bucket. No owner: it cannot delete the
// bucket or touch the aliases, which is what keeps an organization from
// wiping out its own storage by accident.
r = await api("AllowBucketKey", {
  bucketId, accessKeyId: KEY_ID,
  permissions: {read: true, write: true, owner: false},
});
if (!r.ok) { console.error(`AllowBucketKey ${r.status}: ${r.txt}`); process.exit(1); }
console.log(`read+write permission for org-${ORG} on ${BUCKET}: ok`);
