apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: org-canary-secrets
  annotations:
    config.kubernetes.io/function: |
      exec: {path: ksops}
files:
  - secret-regcred-internal.enc.yaml    # fase 40 (derivado atómico)
