# title: the sentinels are written and recognized by the same module
# origin: V-105 (03 §5.6) — new in v3
check() {
# Class B of the register, three cases. The most expensive: the banner
# «GENERADO POR `aegis org`» was written eight times as a literal, and
# the guard that decides whether a derived file was edited by hand
# looked for it with an `in`. Changing the wording in the producer and
# not in the guard breaks nothing visible: the guard stops recognizing
# its own files and hand edits get overwritten in silence.
#
# The rule: if two parts have to recognize the same string, the string
# lives ONCE and both import it.
D105=""
M="$LIBS/aegis/markers.py"
[[ -f "$M" ]] || { fail "lib/aegis/markers.py does not exist — the sentinels have no owner"; return; }
# Nobody else may write these strings by hand.
for sentinel in 'GENERATED BY `aegis org`' '--- DERIVED by aegis-org' '# hash: sha256:'; do
    # -I: a sentinel is TEXT. Without this the sweep matches inside a
    # .pyc and reports a «hand-written copy» that nobody wrote.
    COPIES="$(grep -rlIF "$sentinel" "$LIBS" "$LIBEXEC" 2>/dev/null | grep -v '/markers.py$' || true)"
    [[ -z "$COPIES" ]] \
        || D105="$D105 '$sentinel' written by hand outside markers.py: $(echo "$COPIES" | tr '\n' ' ');"
done
# and the one that RECOGNIZES has to use the same module as the one that writes
grep -q 'markers.is_generated' "$LIBS/aegis/org.py" 2>/dev/null \
    || D105="$D105 the «edited by hand» guard does not use markers.is_generated;"
if [[ -n "$D105" ]]; then fail "sentinels:$D105"
else pass "the sentinels live in lib/aegis/markers.py and both the writer and the recognizer use them"; fi
}
